name: flutter_hex_color
description: HexColor extend Color class to take hex coded value.
version: 2.0.0
homepage: https://github.com/msayed-net/flutter_hex_color

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

# flutter:
#   plugin:
#     platforms:
#       android:
#         package: net.msayed.flutter_hex_color
#         pluginClass: HexColor
#       ios:
#         pluginClass: FlutterHexColorPlugin