name: flutter_hex_color
description: HexColor extend Color class to take hex coded value.
version: 1.0.1
homepage: https://github.com/MohamedSayed95/flutter_hex_color

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: net.msayed.flutter_hex_color
    pluginClass: FlutterHexColorPlugin